server:
  port: 8081

spring:
  application:
    name: "todo-api"
  datasource:
    url: jdbc:mysql://db-p0faj.pub-cdb.ntruss.com:3306/mjconnect?allowPublicKeyRetrieval=true
    username: semyung
    password: tpaud123$


  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.hbm2ddl.auto: update
